[tool.poetry]
name = "art-timelapse"
version = "1.0.0"
description = ""
license = "MIT"
authors = ["cromachina"]

[tool.poetry.dependencies]
python = "^3.13"
numpy = "*"
opencv_python = "*"
pillow = "*"
psd_tools = "*"
pynput = "*"
pyscreenshot = "*"
PyWinCtl = "*"
watchdog = "*"

[tool.poetry.scripts]
art-timelapse = "art_timelapse:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"