name: Build Executable
run-name: ${{ github.ref_name }}

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pyinstaller-build:
    name: Pyinstaller build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: pip install -r requirements.txt

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Run pyinstaller
        run: pyinstaller art_timelapse.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ matrix.os }}
          path: ./dist/**/*
