name: Build Executable
run-name: ${{ github.ref_name }}

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pyinstaller-build:
    name: Pyinstaller build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Create executable
        uses: banduk/pyinstaller-poetry-action@v1
        with:
          python_ver: '3.13.2'
          spec: 'art-timelapse.spec'
          poetry: 'poetry.lock'
          upload_exe_with_name: 'art-timelapse'
          options: -F, --name "main",

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ matrix.os }}
          path: ./dist/**/*
