name: Build Executable
run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.1'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'main'
          options: -F, --name "main",
          
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@975c1b265e11dd76618af1c374e7981f9a6ff44a
        with:
          files: ./artifacts/*
