name: Build Executable

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.1'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'main'
          options: --onefile, --name "main", --windowed, 
